2020-10-22 14:17:13.890 +07:00 [Information] Starting web host
2020-10-22 14:17:14.577 +07:00 [Debug] Hosting starting
2020-10-22 14:17:14.791 +07:00 [Debug] Failed to locate the development https certificate at 'null'.
2020-10-22 14:17:14.857 +07:00 [Debug] Using development certificate: "CN=localhost" (Thumbprint: "9AD2255271162ABFAE3A2FA177EF88703AB40EC4")
2020-10-22 14:17:14.884 +07:00 [Warning] Unable to bind to "https://localhost:5001" on the "IPv4 loopback" interface: '"Сделана попытка доступа к сокету методом, запрещенным правами доступа."'.
2020-10-22 14:17:14.888 +07:00 [Warning] Unable to bind to "http://localhost:5000" on the "IPv4 loopback" interface: '"Сделана попытка доступа к сокету методом, запрещенным правами доступа."'.
2020-10-22 14:17:14.889 +07:00 [Information] Now listening on: "https://localhost:5001"
2020-10-22 14:17:14.889 +07:00 [Information] Now listening on: "http://localhost:5000"
2020-10-22 14:17:14.889 +07:00 [Debug] Loaded hosting startup assembly "WebApi"
2020-10-22 14:17:14.890 +07:00 [Information] Application started. Press Ctrl+C to shut down.
2020-10-22 14:17:14.890 +07:00 [Information] Hosting environment: "Development"
2020-10-22 14:17:14.891 +07:00 [Information] Content root path: "C:\Users\bylyba.ilia\source\repos\WebApi\WebApi"
2020-10-22 14:17:14.892 +07:00 [Debug] Hosting started
2020-10-22 14:17:15.153 +07:00 [Debug] Connection id ""0HM3MBA0BCSAJ"" accepted.
2020-10-22 14:17:15.155 +07:00 [Debug] Connection id ""0HM3MBA0BCSAJ"" started.
2020-10-22 14:17:15.246 +07:00 [Information] Request starting HTTP/2 GET https://localhost:5001/  
2020-10-22 14:17:15.251 +07:00 [Debug] Wildcard detected, all requests with hosts will be allowed.
2020-10-22 14:17:15.268 +07:00 [Debug] No candidates found for the request path '"/"'
2020-10-22 14:17:15.270 +07:00 [Debug] Request did not match any endpoints
2020-10-22 14:17:15.273 +07:00 [Information] Request finished in 28.5491ms 404 
2020-10-22 14:17:41.863 +07:00 [Debug] Connection id ""0HM3MBA0BCSAK"" accepted.
2020-10-22 14:17:41.865 +07:00 [Debug] Connection id ""0HM3MBA0BCSAK"" started.
2020-10-22 14:17:42.468 +07:00 [Information] Request starting HTTP/1.1 POST https://localhost:5001/api/userstatistics application/json 121
2020-10-22 14:17:42.472 +07:00 [Debug] 1 candidate(s) found for the request path '"/api/userstatistics"'
2020-10-22 14:17:42.475 +07:00 [Debug] Endpoint '"WebApi.Controllers.UserStatisticsController.Post (WebApi)"' with route pattern '"api/UserStatistics"' is valid for the request path '"/api/userstatistics"'
2020-10-22 14:17:42.476 +07:00 [Debug] Request matched endpoint '"WebApi.Controllers.UserStatisticsController.Post (WebApi)"'
2020-10-22 14:17:42.477 +07:00 [Information] Executing endpoint '"WebApi.Controllers.UserStatisticsController.Post (WebApi)"'
2020-10-22 14:17:42.485 +07:00 [Debug] Registered model binder providers, in the following order: ["Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.EnumTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CancellationTokenModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ByteArrayModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormCollectionModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider"]
2020-10-22 14:17:42.534 +07:00 [Information] Route matched with "{action = \"Post\", controller = \"UserStatistics\"}". Executing controller action with signature "Void Post(WebApi.Models.UserStatisticsDTO)" on controller "WebApi.Controllers.UserStatisticsController" ("WebApi").
2020-10-22 14:17:42.536 +07:00 [Debug] Execution plan of "authorization" filters (in the following order): ["None"]
2020-10-22 14:17:42.537 +07:00 [Debug] Execution plan of "resource" filters (in the following order): ["None"]
2020-10-22 14:17:42.539 +07:00 [Debug] Execution plan of "action" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)", "Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)"]
2020-10-22 14:17:42.540 +07:00 [Debug] Execution plan of "exception" filters (in the following order): ["None"]
2020-10-22 14:17:42.541 +07:00 [Debug] Execution plan of "result" filters (in the following order): ["Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)"]
2020-10-22 14:17:42.543 +07:00 [Debug] Executing controller factory for controller "WebApi.Controllers.UserStatisticsController" ("WebApi")
2020-10-22 14:17:42.549 +07:00 [Information] Executed action "WebApi.Controllers.UserStatisticsController.Post (WebApi)" in 3.4043ms
2020-10-22 14:17:42.550 +07:00 [Information] Executed endpoint '"WebApi.Controllers.UserStatisticsController.Post (WebApi)"'
2020-10-22 14:17:42.551 +07:00 [Error] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Unable to resolve service for type 'Serilog.ILogger' while attempting to activate 'WebApi.Controllers.UserStatisticsController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-22 14:17:42.605 +07:00 [Debug] Connection id ""0HM3MBA0BCSAK"" completed keep alive response.
2020-10-22 14:17:42.606 +07:00 [Information] Request finished in 138.9819ms 500 text/plain
2020-10-22 14:17:42.607 +07:00 [Debug] Connection id ""0HM3MBA0BCSAK"", Request id ""0HM3MBA0BCSAK:00000001"": started reading request body.
2020-10-22 14:17:42.610 +07:00 [Debug] Connection id ""0HM3MBA0BCSAK"", Request id ""0HM3MBA0BCSAK:00000001"": done reading request body.
2020-10-22 14:17:49.062 +07:00 [Debug] Connection id ""0HM3MBA0BCSAK"" reset.
2020-10-22 14:17:49.064 +07:00 [Debug] Connection id ""0HM3MBA0BCSAK"" sending FIN because: ""The client closed the connection.""
2020-10-22 14:17:49.066 +07:00 [Debug] Connection id ""0HM3MBA0BCSAK"" disconnecting.
2020-10-22 14:17:49.069 +07:00 [Debug] Connection id ""0HM3MBA0BCSAK"" stopped.
2020-10-22 14:19:01.339 +07:00 [Information] Application is shutting down...
2020-10-22 14:19:01.340 +07:00 [Debug] Hosting stopping
2020-10-22 14:19:01.348 +07:00 [Debug] Connection id ""0HM3MBA0BCSAJ"" is closing.
2020-10-22 14:19:01.352 +07:00 [Debug] Connection id ""0HM3MBA0BCSAJ"" is closed. The last processed stream ID was 1.
2020-10-22 14:19:01.354 +07:00 [Debug] Connection id ""0HM3MBA0BCSAJ"" received FIN.
2020-10-22 14:19:01.355 +07:00 [Debug] Connection id ""0HM3MBA0BCSAJ"" stopped.
2020-10-22 14:19:01.356 +07:00 [Debug] Connection id ""0HM3MBA0BCSAJ"" sending FIN because: ""The Socket transport's send loop completed gracefully.""
2020-10-22 14:19:01.359 +07:00 [Debug] Hosting stopped
2020-10-22 14:26:00.202 +07:00 [Information] Starting web host
2020-10-22 14:26:00.600 +07:00 [Debug] Hosting starting
2020-10-22 14:26:00.750 +07:00 [Debug] Failed to locate the development https certificate at 'null'.
2020-10-22 14:26:00.811 +07:00 [Debug] Using development certificate: "CN=localhost" (Thumbprint: "9AD2255271162ABFAE3A2FA177EF88703AB40EC4")
2020-10-22 14:26:00.835 +07:00 [Warning] Unable to bind to "https://localhost:5001" on the "IPv4 loopback" interface: '"Сделана попытка доступа к сокету методом, запрещенным правами доступа."'.
2020-10-22 14:26:00.838 +07:00 [Warning] Unable to bind to "http://localhost:5000" on the "IPv4 loopback" interface: '"Сделана попытка доступа к сокету методом, запрещенным правами доступа."'.
2020-10-22 14:26:00.839 +07:00 [Information] Now listening on: "https://localhost:5001"
2020-10-22 14:26:00.840 +07:00 [Information] Now listening on: "http://localhost:5000"
2020-10-22 14:26:00.841 +07:00 [Debug] Loaded hosting startup assembly "WebApi"
2020-10-22 14:26:00.841 +07:00 [Information] Application started. Press Ctrl+C to shut down.
2020-10-22 14:26:00.842 +07:00 [Information] Hosting environment: "Development"
2020-10-22 14:26:00.843 +07:00 [Information] Content root path: "C:\Users\bylyba.ilia\source\repos\WebApi\WebApi"
2020-10-22 14:26:00.843 +07:00 [Debug] Hosting started
2020-10-22 14:26:01.449 +07:00 [Debug] Connection id ""0HM3MBET6HM7D"" accepted.
2020-10-22 14:26:01.451 +07:00 [Debug] Connection id ""0HM3MBET6HM7D"" started.
2020-10-22 14:26:01.533 +07:00 [Information] Request starting HTTP/2 GET https://localhost:5001/  
2020-10-22 14:26:01.537 +07:00 [Debug] Wildcard detected, all requests with hosts will be allowed.
2020-10-22 14:26:01.554 +07:00 [Debug] No candidates found for the request path '"/"'
2020-10-22 14:26:01.555 +07:00 [Debug] Request did not match any endpoints
2020-10-22 14:26:01.558 +07:00 [Information] Request finished in 26.6233ms 404 
2020-10-22 14:26:10.320 +07:00 [Debug] Connection id ""0HM3MBET6HM7E"" accepted.
2020-10-22 14:26:10.322 +07:00 [Debug] Connection id ""0HM3MBET6HM7E"" started.
2020-10-22 14:26:10.819 +07:00 [Information] Request starting HTTP/1.1 GET https://localhost:5001/api/userstatistics  
2020-10-22 14:26:10.824 +07:00 [Debug] 1 candidate(s) found for the request path '"/api/userstatistics"'
2020-10-22 14:26:10.827 +07:00 [Debug] Endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"' with route pattern '"api/UserStatistics"' is valid for the request path '"/api/userstatistics"'
2020-10-22 14:26:10.828 +07:00 [Debug] Request matched endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"'
2020-10-22 14:26:10.829 +07:00 [Information] Executing endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"'
2020-10-22 14:26:10.837 +07:00 [Debug] Registered model binder providers, in the following order: ["Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.EnumTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CancellationTokenModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ByteArrayModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormCollectionModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider", "Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider"]
2020-10-22 14:26:10.879 +07:00 [Information] Route matched with "{action = \"Get\", controller = \"UserStatistics\"}". Executing controller action with signature "System.String Get()" on controller "WebApi.Controllers.UserStatisticsController" ("WebApi").
2020-10-22 14:26:10.881 +07:00 [Debug] Execution plan of "authorization" filters (in the following order): ["None"]
2020-10-22 14:26:10.882 +07:00 [Debug] Execution plan of "resource" filters (in the following order): ["None"]
2020-10-22 14:26:10.883 +07:00 [Debug] Execution plan of "action" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)", "Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)"]
2020-10-22 14:26:10.884 +07:00 [Debug] Execution plan of "exception" filters (in the following order): ["None"]
2020-10-22 14:26:10.886 +07:00 [Debug] Execution plan of "result" filters (in the following order): ["Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)"]
2020-10-22 14:26:10.888 +07:00 [Debug] Executing controller factory for controller "WebApi.Controllers.UserStatisticsController" ("WebApi")
2020-10-22 14:26:10.893 +07:00 [Information] Executed action "WebApi.Controllers.UserStatisticsController.Get (WebApi)" in 2.9738ms
2020-10-22 14:26:10.895 +07:00 [Information] Executed endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"'
2020-10-22 14:26:10.896 +07:00 [Error] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Unable to resolve service for type 'Serilog.ILogger' while attempting to activate 'WebApi.Controllers.UserStatisticsController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-22 14:26:10.945 +07:00 [Debug] Connection id ""0HM3MBET6HM7E"" completed keep alive response.
2020-10-22 14:26:10.946 +07:00 [Information] Request finished in 126.7119ms 500 text/plain
2020-10-22 14:26:11.217 +07:00 [Debug] Connection id ""0HM3MBET6HM7F"" accepted.
2020-10-22 14:26:11.218 +07:00 [Debug] Connection id ""0HM3MBET6HM7F"" started.
2020-10-22 14:26:11.223 +07:00 [Information] Request starting HTTP/1.1 GET https://localhost:5001/api/userstatistics  
2020-10-22 14:26:11.224 +07:00 [Debug] 1 candidate(s) found for the request path '"/api/userstatistics"'
2020-10-22 14:26:11.225 +07:00 [Debug] Endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"' with route pattern '"api/UserStatistics"' is valid for the request path '"/api/userstatistics"'
2020-10-22 14:26:11.228 +07:00 [Debug] Request matched endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"'
2020-10-22 14:26:11.229 +07:00 [Information] Executing endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"'
2020-10-22 14:26:11.230 +07:00 [Information] Route matched with "{action = \"Get\", controller = \"UserStatistics\"}". Executing controller action with signature "System.String Get()" on controller "WebApi.Controllers.UserStatisticsController" ("WebApi").
2020-10-22 14:26:11.232 +07:00 [Debug] Execution plan of "authorization" filters (in the following order): ["None"]
2020-10-22 14:26:11.232 +07:00 [Debug] Execution plan of "resource" filters (in the following order): ["None"]
2020-10-22 14:26:11.234 +07:00 [Debug] Execution plan of "action" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)", "Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)"]
2020-10-22 14:26:11.236 +07:00 [Debug] Execution plan of "exception" filters (in the following order): ["None"]
2020-10-22 14:26:11.237 +07:00 [Debug] Execution plan of "result" filters (in the following order): ["Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)"]
2020-10-22 14:26:11.239 +07:00 [Debug] Executing controller factory for controller "WebApi.Controllers.UserStatisticsController" ("WebApi")
2020-10-22 14:26:11.240 +07:00 [Information] Executed action "WebApi.Controllers.UserStatisticsController.Get (WebApi)" in 1.2937ms
2020-10-22 14:26:11.241 +07:00 [Information] Executed endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"'
2020-10-22 14:26:11.242 +07:00 [Error] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Unable to resolve service for type 'Serilog.ILogger' while attempting to activate 'WebApi.Controllers.UserStatisticsController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-22 14:26:11.252 +07:00 [Debug] Connection id ""0HM3MBET6HM7F"" completed keep alive response.
2020-10-22 14:26:11.252 +07:00 [Information] Request finished in 29.6222ms 500 text/plain
2020-10-22 14:26:16.034 +07:00 [Debug] Connection id ""0HM3MBET6HM7G"" accepted.
2020-10-22 14:26:16.035 +07:00 [Debug] Connection id ""0HM3MBET6HM7G"" started.
2020-10-22 14:26:16.038 +07:00 [Information] Request starting HTTP/1.1 GET https://localhost:5001/api/userstatistics  
2020-10-22 14:26:16.038 +07:00 [Debug] 1 candidate(s) found for the request path '"/api/userstatistics"'
2020-10-22 14:26:16.039 +07:00 [Debug] Endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"' with route pattern '"api/UserStatistics"' is valid for the request path '"/api/userstatistics"'
2020-10-22 14:26:16.040 +07:00 [Debug] Request matched endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"'
2020-10-22 14:26:16.041 +07:00 [Information] Executing endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"'
2020-10-22 14:26:16.042 +07:00 [Information] Route matched with "{action = \"Get\", controller = \"UserStatistics\"}". Executing controller action with signature "System.String Get()" on controller "WebApi.Controllers.UserStatisticsController" ("WebApi").
2020-10-22 14:26:16.044 +07:00 [Debug] Execution plan of "authorization" filters (in the following order): ["None"]
2020-10-22 14:26:16.044 +07:00 [Debug] Execution plan of "resource" filters (in the following order): ["None"]
2020-10-22 14:26:16.045 +07:00 [Debug] Execution plan of "action" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)", "Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)"]
2020-10-22 14:26:16.047 +07:00 [Debug] Execution plan of "exception" filters (in the following order): ["None"]
2020-10-22 14:26:16.047 +07:00 [Debug] Execution plan of "result" filters (in the following order): ["Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)"]
2020-10-22 14:26:16.048 +07:00 [Debug] Executing controller factory for controller "WebApi.Controllers.UserStatisticsController" ("WebApi")
2020-10-22 14:26:16.050 +07:00 [Information] Executed action "WebApi.Controllers.UserStatisticsController.Get (WebApi)" in 1.2023ms
2020-10-22 14:26:16.050 +07:00 [Information] Executed endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"'
2020-10-22 14:26:16.051 +07:00 [Error] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Unable to resolve service for type 'Serilog.ILogger' while attempting to activate 'WebApi.Controllers.UserStatisticsController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-22 14:26:16.058 +07:00 [Debug] Connection id ""0HM3MBET6HM7G"" completed keep alive response.
2020-10-22 14:26:16.059 +07:00 [Information] Request finished in 21.041ms 500 text/plain
2020-10-22 14:26:16.081 +07:00 [Debug] Connection id ""0HM3MBET6HM7H"" accepted.
2020-10-22 14:26:16.081 +07:00 [Debug] Connection id ""0HM3MBET6HM7H"" started.
2020-10-22 14:26:16.085 +07:00 [Information] Request starting HTTP/1.1 GET https://localhost:5001/api/userstatistics  
2020-10-22 14:26:16.085 +07:00 [Debug] 1 candidate(s) found for the request path '"/api/userstatistics"'
2020-10-22 14:26:16.086 +07:00 [Debug] Endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"' with route pattern '"api/UserStatistics"' is valid for the request path '"/api/userstatistics"'
2020-10-22 14:26:16.087 +07:00 [Debug] Request matched endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"'
2020-10-22 14:26:16.088 +07:00 [Information] Executing endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"'
2020-10-22 14:26:16.089 +07:00 [Information] Route matched with "{action = \"Get\", controller = \"UserStatistics\"}". Executing controller action with signature "System.String Get()" on controller "WebApi.Controllers.UserStatisticsController" ("WebApi").
2020-10-22 14:26:16.091 +07:00 [Debug] Execution plan of "authorization" filters (in the following order): ["None"]
2020-10-22 14:26:16.092 +07:00 [Debug] Execution plan of "resource" filters (in the following order): ["None"]
2020-10-22 14:26:16.093 +07:00 [Debug] Execution plan of "action" filters (in the following order): ["Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)", "Microsoft.AspNetCore.Mvc.Infrastructure.ModelStateInvalidFilter (Order: -2000)"]
2020-10-22 14:26:16.094 +07:00 [Debug] Execution plan of "exception" filters (in the following order): ["None"]
2020-10-22 14:26:16.095 +07:00 [Debug] Execution plan of "result" filters (in the following order): ["Microsoft.AspNetCore.Mvc.Infrastructure.ClientErrorResultFilter (Order: -2000)"]
2020-10-22 14:26:16.096 +07:00 [Debug] Executing controller factory for controller "WebApi.Controllers.UserStatisticsController" ("WebApi")
2020-10-22 14:26:16.097 +07:00 [Information] Executed action "WebApi.Controllers.UserStatisticsController.Get (WebApi)" in 1.1795ms
2020-10-22 14:26:16.098 +07:00 [Information] Executed endpoint '"WebApi.Controllers.UserStatisticsController.Get (WebApi)"'
2020-10-22 14:26:16.099 +07:00 [Error] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: Unable to resolve service for type 'Serilog.ILogger' while attempting to activate 'WebApi.Controllers.UserStatisticsController'.
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
2020-10-22 14:26:16.106 +07:00 [Debug] Connection id ""0HM3MBET6HM7H"" completed keep alive response.
2020-10-22 14:26:16.106 +07:00 [Information] Request finished in 21.3827ms 500 text/plain
2020-10-22 14:26:20.026 +07:00 [Information] Application is shutting down...
2020-10-22 14:26:20.027 +07:00 [Debug] Hosting stopping
2020-10-22 14:26:20.031 +07:00 [Debug] Connection id ""0HM3MBET6HM7D"" is closing.
2020-10-22 14:26:20.044 +07:00 [Debug] Connection id ""0HM3MBET6HM7F"" disconnecting.
2020-10-22 14:26:20.044 +07:00 [Debug] Connection id ""0HM3MBET6HM7H"" disconnecting.
2020-10-22 14:26:20.044 +07:00 [Debug] Connection id ""0HM3MBET6HM7E"" disconnecting.
2020-10-22 14:26:20.044 +07:00 [Debug] Connection id ""0HM3MBET6HM7G"" disconnecting.
2020-10-22 14:26:20.046 +07:00 [Debug] Connection id ""0HM3MBET6HM7D"" is closed. The last processed stream ID was 1.
2020-10-22 14:26:20.047 +07:00 [Debug] Connection id ""0HM3MBET6HM7D"" received FIN.
2020-10-22 14:26:20.048 +07:00 [Debug] Connection id ""0HM3MBET6HM7E"" stopped.
2020-10-22 14:26:20.048 +07:00 [Debug] Connection id ""0HM3MBET6HM7F"" stopped.
2020-10-22 14:26:20.048 +07:00 [Debug] Connection id ""0HM3MBET6HM7H"" stopped.
2020-10-22 14:26:20.052 +07:00 [Debug] Connection id ""0HM3MBET6HM7F"" sending FIN because: ""The Socket transport's send loop completed gracefully.""
2020-10-22 14:26:20.048 +07:00 [Debug] Connection id ""0HM3MBET6HM7G"" stopped.
2020-10-22 14:26:20.052 +07:00 [Debug] Connection id ""0HM3MBET6HM7H"" sending FIN because: ""The Socket transport's send loop completed gracefully.""
2020-10-22 14:26:20.048 +07:00 [Debug] Connection id ""0HM3MBET6HM7D"" stopped.
2020-10-22 14:26:20.054 +07:00 [Debug] Connection id ""0HM3MBET6HM7G"" sending FIN because: ""The Socket transport's send loop completed gracefully.""
2020-10-22 14:26:20.052 +07:00 [Debug] Connection id ""0HM3MBET6HM7E"" sending FIN because: ""The Socket transport's send loop completed gracefully.""
2020-10-22 14:26:20.055 +07:00 [Debug] Connection id ""0HM3MBET6HM7D"" sending FIN because: ""The Socket transport's send loop completed gracefully.""
2020-10-22 14:26:20.058 +07:00 [Debug] Hosting stopped
2020-10-22 14:49:56.271 +07:00 [Information] Starting web host
2020-10-22 14:50:29.271 +07:00 [Information] Starting web host
